main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
]

news/urls.py
from django.urls import path

from . import views

app_name = "news"
urlpatterns = [
    path("", views.NewsListView.as_view(), name="index"),
    path("<int:pk>/", views.NewsDetailView.as_view(), name="detail"),
]

textquery/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("news/", include("news.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crawlers/models.py
from django.db import models

# Create your models here.
class Crawler(models.Model):
    name = models.CharField(max_length=100)
    allowed_domain = models.CharField(max_length=100)
    start_url = models.CharField(max_length=180)
    start_url_search = models.CharField(max_length=180)
    url = models.CharField(max_length=180)
    css_all_newsdiv = models.CharField(max_length=180)
    css_search_newsdiv = models.CharField(max_length=180)
    title_css = models.CharField(max_length=180)
    pub_date_css = models.CharField(max_length=180)
    body_css = models.CharField(max_length=180)
    image_xpath = models.CharField(max_length=180)

    def __str__(self):
        return self.name

    class Meta:
        managed = True

main/models.py
from django.db import models

# Create your models here.

news/models.py
from statistics import mode
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=180)
    url = models.CharField(max_length=200, unique=True)
    pub_date = models.CharField(max_length=50)
    body = models.TextField()
    site = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        managed = True


class NewsImage(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=200)

    def __str__(self):
        return "Image for: " + self.news.title + ". Url: " + self.image_url

    class Meta:
        managed = True


class Entity(models.Model):
    name = models.CharField(max_length=50)
    news = models.ForeignKey(News, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        managed = True

crawlers/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = "main/index.html"

news/views.py
from multiprocessing import Pool
from crawlers.models import Crawler
from news.models import Entity, News, NewsImage
from django.views.generic import ListView, DetailView
from django.db.models import Q

from textquerycrawlers.textquerycrawlers.startCrawlingSpecific import (
    startCrawlingSpecific,
)

# Create your views here.


def remove_dupes(my_list):
    newlist = [my_list[0]]
    for e in my_list:
        flag = True
        for e2 in newlist:
            if e2.name == e.name:
                flag = False
                break

        if flag:
            newlist.append(e)

    return newlist


class NewsListView(ListView):
    model = News
    template_name = "news/news_list.html"
    context_object_name = "news_list"
    paginate_by = 12

    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        sort = self.request.GET.get("sortby")
        order = self.request.GET.get("order")
        crawl = self.request.GET.get("crawl")
        object_list = News.objects.order_by("-pub_date")

        if crawl == "true" and query:
            try:
                # Start crawling in a separate
                crawlers = Crawler.objects.all()
                for crawler in crawlers:
                    print(crawler.allowed_domain)
                    pool = Pool(processes=1)
                    pool.apply_async(
                        startCrawlingSpecific,
                        args=(
                            crawler.allowed_domain,
                            crawler.start_url_search,
                            crawler.url,
                            crawler.css_search_newsdiv,
                            crawler.title_css,
                            crawler.pub_date_css,
                            crawler.body_css,
                            crawler.image_xpath,
                            query,
                        ),
                    )
            except Exception as e:
                print(e)

        if query:
            object_list = News.objects.filter(
                Q(title__icontains=query) | Q(body__icontains=query)
            )

        if sort and order:
            if order == "asc":
                object_list = object_list.order_by(sort)
            else:
                object_list = object_list.order_by("-" + sort)

        # Add imageurl to object_list
        for news in object_list:
            if NewsImage.objects.filter(news=news).first():
                news.imageurl = NewsImage.objects.filter(news=news).first().image_url

        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # entities = self.object_list
        entities = Entity.objects.filter(news__in=self.object_list)

        if not entities:
            return context

        for entity in entities:
            entity.count = entities.filter(name=entity.name).count()

        context["entity_list"] = sorted(
            remove_dupes(entities), key=lambda x: x.count, reverse=True
        )

        return context


class NewsDetailView(DetailView):
    model = News
    template_name = "news/news_detail.html"
    context_object_name = "news_detail"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news_images"] = NewsImage.objects.filter(news=self.object)

        entities = Entity.objects.filter(news=self.object)

        if not entities:
            return context

        for entity in entities:
            entity.count = entities.filter(name=entity.name).count()

        context["entities"] = sorted(
            remove_dupes(entities), key=lambda x: x.count, reverse=True
        )

        return context

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--Bulma-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    />
    <!--Chart js-->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
      integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
      integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E="
      crossorigin="anonymous"
    />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css"
    />

    <!-- Bulma icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css"
    />

    <!-- Bulma carousel -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.4/dist/css/bulma-carousel.min.css"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.4/dist/js/bulma-carousel.min.js"
    ></script>

    <link rel="stylesheet" href={% static 'main/style/style.css' %} />
    {% block style %}
    {% endblock %}
    <title>TextQuery</title>
  </head>
  <body>
    {% include 'navbar.html' %} {% block content %} {% endblock%}
    {% include 'footer.html' %}
  </body>
  <script>
    $(document).ready(function () {
      // Check for click events on the navbar burger icon
      $(".navbar-burger").click(function () {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        $(".navbar-burger").toggleClass("is-active");
        $(".navbar-menu").toggleClass("is-active");
      });
    });
  </script>
  {% block scripts %} {% endblock %}
</html>

main/templates/footer.html
<footer class="hero">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column is-4">
          <div class="content">
            <h6 class="footer_title title is-6">
              You want to receive the latest info?
            </h6>
            <p>
              Then you can subscribe to our newsletter! Just enter your email
              and we will send you the latest news.
            </p>
            <div class="newsletter">
              <form
                action="mailto:smart@codingburgas.bg"
                method="POST"
                class="newsletter-form"
              >
                <input
                  type="email"
                  name="email"
                  placeholder="Enter your email!"
                />
                <button>
                  <i class="fa fa-paper-plane"></i>
                </button>
              </form>
            </div>
          </div>
        </div>
        <div class="column is-4" style="text-align: center">
          <div class="content">
            <div>
              <h6 class="footer_title title is-6">SOCIAL MEDIAS</h6>
              <p>Follow us on our social media!</p>
              <a class="button is-medium is-facebook">
                <span class="icon">
                  <i class="fab fa-facebook-f fa-lg"></i>
                </span>
              </a>
              <a class="button is-medium is-foursquare">
                <span class="icon">
                  <i class="fab fa-instagram fa-lg"></i>
                </span>
              </a>
              <a class="button is-medium is-twitter">
                <span class="icon">
                  <i class="fab fa-twitter fa-lg"></i>
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="column is-4">
          <div class="content">
            <h6 class="footer_title title is-6">Contact us!</h6>
            <p>
              If you want us to add, change or update any news, you can contact
              us at:
              <br />
              Phone: +359 888 888 888
              <br />
              Email: smart@codingburgas.bg
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="hero-foot">
    <div class="container has-text-centered">
      <p class="footer-text">&copy; 2022 - TextQuery</p>
    </div>
  </div>
  <br />
</footer>

main/templates/main/index.html
{% extends "base.html" %} {% load static %} {% block content%}
<section class="hero main_hero is-fullheight banner">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-1 main-text">
        This is a website for
        <span class="typed-text" style="color: #ed1e79"></span
        ><span class="cursor">&nbsp;</span>
      </h1>
    </div>
  </div>
</section>
<section style="margin: 5%">
  <div>
    <p class="title is-3">What is the purpose of our project??</p>
    <br />
    <p>
      Powered by AI, our project has the goal to provide citizens with quick and
      easy access to the news that they consider important. They can sort,
      filter and display statistics for each one of them!
    </p>
  </div>
</section>

<section class="hero" style="margin-right: 22%; margin-left: 3%">
  <div class="hero-body">
    <div class="container">
      <p class="title is-3 has-text-centered">Our team</p>
      <br /><br /><br />
      <div class="columns has-text-centered">
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img
                  src="{% static 'main/images/avatars/Stoyan.png'%}"
                  alt="Stoyan Ivanov"
                />
              </figure>
            </div>
            <div class="card-content box">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4" style="padding-bottom: 10px">
                    Stoyan Ivanov
                  </p>
                  <p class="subtitle is-6">@SSIvanov19</p>
                </div>
              </div>

              <div class="content">
                Stoyan is our main Web Developer. His main task was to create
                the platform behind our project. Also deployed the entire
                project to Azure. You can see his
                <a href="https://github.com/SSIvanov19" target="_blanck"
                  >GitHub profile</a
                >
                for more information.
                <br /><br />
                <a>#Web</a> <a>#Django</a> <a>#Deployment</a> <a>#Azure</a>
              </div>
            </div>
          </div>
        </div>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img
                  src="{% static 'main/images/avatars/Rado.png'%}"
                  alt="Radoslav Lisitsov"
                />
              </figure>
            </div>
            <div class="card-content box">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4" style="padding-bottom: 10px">
                    Radoslav Lisitsov
                  </p>
                  <p class="subtitle is-6">@RPLisitsov19</p>
                </div>
              </div>

              <div class="content">
                Radoslav is one of our Front-End Developers and his task was to
                create UI (User Interface) for our web platform using Bulma. You
                can see his
                <a href="https://github.com/RPLisitsov19" target="_blanck"
                  >GitHub profile</a
                >
                for more information.
                <br /><br /><br /><br />
                <a>#FrontEnd</a> <a>#UI</a> <a>#Bulma</a>
              </div>
            </div>
          </div>
        </div>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img
                  src="{% static 'main/images/avatars/Petar_n.png'%}"
                  alt="Petar Nikolov"
                />
              </figure>
            </div>
            <div class="card-content box">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4" style="padding-bottom: 10px">
                    Petar Nikolov
                  </p>
                  <p class="subtitle is-6">@PRNikolov19</p>
                </div>
              </div>

              <div class="content">
                Petar Nikolov is one of our Front-End Developers and his task
                was to create UI (User Interface) for our web platform using
                Bulma. You can see his
                <a href="https://github.com/PRNikolov19" target="_blanck"
                  >GitHub profile</a
                >
                for more information.
                <br /><br /><br /><br />
                <a>#FrontEnd</a> <a>#UI</a> <a>#Bulma</a>
              </div>
            </div>
          </div>
        </div>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img
                  src="{% static 'main/images/avatars/Petar_s.png'%}"
                  alt="Petar Spasov"
                />
              </figure>
            </div>
            <div class="card-content box">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4" style="padding-bottom: 10px">
                    Petar Spasov
                  </p>
                  <p class="subtitle is-6">@PZSpasov19</p>
                </div>
              </div>

              <div class="content">
                Petar Spasov had to make sure everyone got their assignments
                done on time, help them when they needed it, and do presentation
                and documentation. You can see his
                <a href="https://github.com/PZSpasov19" target="_blanck"
                  >GitHub profile</a
                >
                for more info.
                <br /><br />
                <a>#ScrumTrainer</a> <a>#Organisation</a>
              </div>
            </div>
          </div>
        </div>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img
                  src="{% static 'main/images/avatars/Kaloyan.png'%}"
                  alt="Kaloyan Pazlamachev"
                />
              </figure>
            </div>
            <div class="card-content box">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4" style="padding-bottom: 10px">
                    Kaloyan Pazlamachev
                  </p>
                  <p class="subtitle is-6">@KNPazlamachev19</p>
                </div>
              </div>

              <div class="content">
                Kaloyan is our QA (Quality Assurance). His main task was to
                insure our project run fine, without any problems. For this
                purpose he has created some unit-tests. You can see his
                <a href="https://github.com/KNPazlamachev19" target="_blanck"
                  >GitHub profile</a
                >
                for more information.
                <br /><br />
                <a>#QA</a> <a>#Django</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %} {% block scripts %}
<script>
  const typedTextSpan = document.querySelector(".typed-text");
  const cursorSpan = document.querySelector(".cursor");

  const textArray = ["news!", "information!", "statistics!"];
  const typingDelay = 100;
  const erasingDelay = 100;
  const newTextDelay = 1700;
  let textArrayIndex = 0;
  let charIndex = 0;

  function type() {
    if (charIndex < textArray[textArrayIndex].length) {
      if (!cursorSpan.classList.contains("typing"))
        cursorSpan.classList.add("typing");
      typedTextSpan.textContent += textArray[textArrayIndex].charAt(charIndex);
      charIndex++;
      setTimeout(type, typingDelay);
    } else {
      cursorSpan.classList.remove("typing");
      setTimeout(erase, newTextDelay);
    }
  }

  function erase() {
    if (charIndex > 0) {
      if (!cursorSpan.classList.contains("typing"))
        cursorSpan.classList.add("typing");
      typedTextSpan.textContent = textArray[textArrayIndex].substring(
        0,
        charIndex - 1
      );
      charIndex--;
      setTimeout(erase, erasingDelay);
    } else {
      cursorSpan.classList.remove("typing");
      textArrayIndex++;
      if (textArrayIndex >= textArray.length) textArrayIndex = 0;
      setTimeout(type, typingDelay + 1100);
    }
  }

  document.addEventListener("DOMContentLoaded", function () {
    if (textArray.length) setTimeout(type, newTextDelay + 250);
  });
</script>
{% endblock %}

main/templates/navbar.html
{% load static %}
<nav>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{%url 'main:index' %}">
        <img src="{% static 'main/images/logo/large_textquery_logo.png'%}" />
      </a>

      <a
        role="button"
        class="navbar-burger"
        aria-label="menu"
        aria-expanded="false"
        data-target="navbarBasicExample"
      >
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{%url 'main:index' %}"> Home </a>

        <a class="navbar-item" href="{%url 'news:index' %}"> News </a>
      </div>
    </div>
  </nav>
</nav>

news/templates/news/news_detail.html
{% extends 'base.html' %} {% load random_numbers %} {% block content %}
<section class="section">
  <div class="container">
    <button class="button is-primary" onclick="window.location.href='/news/'">
      <- Back
    </button>
    <button class="button is-link" onclick="window.location.href='{{news_detail.url}}'">
        Go to source
    </button>
    <div class="collumns">
      <div class="column is-half-desktop">
        {% for image in news_images %}
        <img
          src="{{ image.image_url }}"
          alt="There is not image for this news"
        />
        {% endfor %}
      </div>
      <div class="column">
        <h1 class="title">{{ news_detail.title }}</h1>
        <p class="subtitle">{{ news_detail.pub_date }}</p>
        {% autoescape off %}
        <p style="text-align: justify">{{ news_detail.body }}</p>
        {% endautoescape %}
      </div>
    </div>
  </div>
  <canvas id="pie" width="400" height="100"></canvas>
  <br />
  <br />
  <canvas id="bar" width="400" height="100"></canvas>
</section>
<!--

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% for image in news_images %}
                <img src="{{image.image_url}}" />
                {% endfor %}
      <h1>{{news_detail.title}}</h1>
      <p>Published at: {{news_detail.pub_date}}</p>
      {% autoescape off %}
      <p>{{news_detail.body}}</p>
      {% endautoescape %}
      <a href="{{news_detail.url}}">Source</a>
      <br />
      <br />

    </div>
</div>
</div>
-->
{% endblock %} {% block scripts %}
<script>
  $(document).ready(() => {
          let pieCtx = document.getElementById('pie').getContext('2d');
          let pie = new Chart(pieCtx, {
              type: 'doughnut',
              data: {
                  labels: [{%for person in entities%}'{{person.name}}',{%endfor%}],
                  datasets: [{
                      label: 'People or organisation mention in this article',
                      data: [{%for person in entities%}{{person.count}},{%endfor%}],
                      backgroundColor: [
                      {%for person in entities %}
                      'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
                      ],
                      borderColor: [
                      {%for person in entities %}
                      'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
                      ],
                      borderWidth: 1
                  }]
              },
              options: {
                  scales: {
                      y: {
                          beginAtZero: true
                      }
                  }
              }
          }
         );

         let barCtx = document.getElementById('bar').getContext('2d');
         let bar = new Chart(barCtx, {
             type: 'bar',
             data: {
                 labels: [{%for person in entities%}'{{person.name}}',{%endfor%}],
                 datasets: [{
                     label: 'People or organisation mention in this article',
                     data: [{%for person in entities%}{{person.count}},{%endfor%}],
                     backgroundColor: [
                     {%for person in entities %}
                     'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
                      ],
                     borderColor: [
                     {%for person in entities %}
                     'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
                     ],
                     borderWidth: 1
                 }]
             },
             options: {
              scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
             }
         }
        );
      });
</script>
{% endblock %}

news/templates/news/news_list.html
{% extends 'base.html' %}
{% load random_numbers %}
{% block content %}

<section class="section">
  <div class="container">

    <form action="{% url 'news:index' %}" method="get">
      {{ formset.management_form }}
      <input class="input" name="q" id="q" type="text" placeholder="Search..." value={{request.GET.q}}>
      <div class="field is-grouped" style="margin-top: 1%">
        <label class="label" for="sortby" style="margin-top: 0.5%; margin-right: 0.5%">Sort by:</label>
        <div class="select">
          <select name="sortby" id="sortby">
            <option value="pub_date">Published date</option>
            <option value="title">Title</option>
          </select>
        </div>

        <label class="label" for="order" style="margin-top: 0.5%; margin-right: 0.5%; margin-left: 1%">Order:</label>
        <div class="select">
          <select name="order" id="order">
            <option value="desc">Descending</option>
            <option value="asc">Ascending</option>
          </select>
        </div>
        <div class="control" style="margin-left: 1%">
          <input class="button is-link"type="submit" value="Search">
        </div>
        <div class="control" style="margin-left: 0.3%">
          <button class="button is-danger is-light" type="button" id="crawlbutton">Start crawing</button>
        </div>
      </div>
    </form>
  </div>
</section>

<section class="hero-section">
  <div class="card-grid">
    {% for news in object_list %}
      <a class="card" href={% url 'news:detail' pk=news.pk %}>
        <div class="card__background" style="background-image: url({{news.imageurl}})"></div>
        <div class="card__content">
          <p class="card__category">{{ news.pub_date }}</p>
          <h3 class="card__heading">{{ news.title|slice:":50" }}...</h3>
        </div>
      </a>
    {% endfor %}
  </div>
</section>

<nav class="pagination is-centered" role="navigation" aria-label="pagination" style="margin-left: 15%;margin-right: 15%;">
  {% if page_obj.has_previous %}
  <a class="pagination-previous" href="?page=1&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">First page</a>
  <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">Previous page</a>
  {% endif %}
  <ul class="pagination-list">
    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>
  </ul>
  {% if page_obj.has_next %}
  <a class="pagination-next" href="?page={{ page_obj.next_page_number }}&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">Next page</a>
  <a class="pagination-next" href="?page={{ page_obj.paginator.num_pages }}&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">Last page</a>
  {% endif %}
</nav>
<!--

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}&q={{request.GET.q}}&order={{request.GET.order}}&sortby={{request.GET.sortby}}">last &raquo;</a>
    {% endif %}
  </span>
</div>
-->
<!--
    <ul>
      {% for news in object_list %}
      <li><a href={% url 'news:detail' pk=news.pk%}>{{ news.title }}</a></li>
      {% empty %}
      <li>No news found! Maybe you want to search for some?</li>
      {% endfor %}
    </ul>


      -->
<canvas id="myChart" width="400" height="100"></canvas>
<canvas id="bar" width="400" height="100"></canvas>
{% endblock %}
{% block style %}
{% load static %}
<link rel="stylesheet" href={% static 'main/style/news.css' %} />
{% endblock %}
{% block scripts %}
<script>
  document.getElementById("crawlbutton").addEventListener("click", () => {
    window.location.href = `?crawl=true&q=${document.getElementById("q").value}`;
  })

  $(document).ready(() => {
          let ctx = document.getElementById('myChart').getContext('2d');
          let myChart = new Chart(ctx, {
              type: 'doughnut',
              data: {
                  labels: [{%for person in entity_list%}'{{person.name}}',{%endfor%}],
                  datasets: [{
                      label: 'People or organisation mentioned in the news',
                      data: [{%for person in entity_list%}{{person.count}},{%endfor%}],
                      backgroundColor: [
                      {%for person in entity_list %}
                      'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
                      ],
                      borderColor: [
                      {%for person in entity_list %}
                      'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
                      ],
                      borderWidth: 1
                  }]
              },
              options: {
                  scales: {
                      y: {
                          beginAtZero: true
                      }
                  }
              }
          }
  );
  let barCtx = document.getElementById('bar').getContext('2d');
  let bar = new Chart(barCtx, {
      type: 'bar',
      data: {
          labels: [{%for person in entity_list%}'{{person.name}}',{%endfor%}],
          datasets: [{
              label: 'People or organisation mentioned in the news',
              data: [{%for person in entity_list%}{{person.count}},{%endfor%}],
              backgroundColor: [
              {%for person in entity_list %}
              'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
               ],
              borderColor: [
              {%for person in entity_list %}
              'rgba({% random_int 1 255 %}, {% random_int 1 255 %}, {% random_int 1 255 %}, 0.2)',{% endfor %}
              ],
              borderWidth: 1
          }]
      },
      options: {
        scales: {
          yAxes: [{
              ticks: {
                  beginAtZero: true
              }
          }]
      }
      }
  }
 );
      });
</script>
{% endblock %}